# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "nfs" do |node|
      node.vm.box = "bento/ubuntu-22.04"
      node.vm.hostname = "nfs"
      node.vm.network :private_network, ip: "192.168.44.16"
      node.vm.provider "virtualbox" do |v|
        v.name = "nfs"
        v.memory = 2048
        v.cpus = 2
        v.linked_clone = true
      end
      
    end

end
