# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "web1" do |node|
      node.vm.box = "bento/ubuntu-22.04"
      node.vm.hostname = "web1"
      node.vm.network :private_network, ip: "192.168.44.10"
      node.vm.provider "virtualbox" do |v|
        v.name = "web1"
        v.memory = 2048
        v.cpus = 2
        v.linked_clone = true
      end
      node.vm.provision "shell", path: "./provision/web.sh"

      # the box generic/alpine might not have shared folders by default
      #node.vm.synced_folder "app/", "/var/www/html"
    end

end
