# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "websocket" do |node|
      node.vm.box = "bento/ubuntu-22.04"
      node.vm.hostname = "web2bsocket"
      node.vm.network :private_network, ip: "192.168.44.13"
      node.vm.provider "virtualbox" do |v|
        v.name = "web2bsocket"
        v.memory = 2048
        v.cpus = 2
        v.linked_clone = true
      end
      node.vm.provision "shell", path: "./provision/web.sh"

     
    end

end
